FROM ubuntu:20.04

RUN apt-get update && apt-get install -y icecast2 && apt-get clean

COPY icecast.xml /etc/icecast2/icecast.xml
COPY start.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 8000

CMD ["/start.sh"]